# GLOBAL SITE SETTINGS

# General
seo_title: "Planet Software Australia"
title: "Planet Software"
company: "Planet Software"
description: ""

# Contact Info
email: info@planetsoftware.com.au
phone: +61 8 8443 6499
fax: +61 8 8352 7572
address: "Planet Software Pty Ltd<br> 82 Rose Street<br> Mile End SA 5031 Australia"

# Social Networks
facebook: "http://www.facebook.com/planetsoftwareaustralia"
linked_in: "http://www.linkedin.com/company/planet-software"
google_plus: "https://plus.google.com/110179816396087474953/posts"
skype: "skype:planetsoftwareadelaide?call"
pin_point: "http://pinpoint.microsoft.com/en-AU/PartnerDetails.aspx?PartnerId=4295488851"
rss: "http://blogs.planetsoftware.com.au/MainFeed.aspx"

# Google Map
google_map: "https://www.google.com.au/maps?q=82+Rose+Street+Mile+End,+South+Australia+5031&ll=-34.921953,138.570879&spn=0.014093,0.033023&oe=utf-8&client=firefox-a&hnear=82+Rose+St,+Mile+End+South+Australia+5031&gl=au&t=h&z=16"

# Google Analytics
google_analytics: "UA-XXXXXXXX-X"